name: universal ci
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  install-sdk:
    strategy:
      matrix:
        os: ['macos-13', 'macos-14', 'macos-15']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Check emulator"
        run: |
          sdkmanager "tools"
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-28"
          sdkmanager "system-images;android-28;default;x86"
          sdkmanager --update
          sdkmanager --licenses
          avdmanager create avd -n test -k "system-images;android-28;default;x86" -c 200M -f
          emulator -avd test -no-audio -no-accel -no-snapshot -no-window -camera-back none -camera-front none
      - name: "Install SDK"
        run: |
          HOST_TOOLCHAIN_URL="https://download.swift.org/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2025-08-08-a/swift-DEVELOPMENT-SNAPSHOT-2025-08-08-a-osx.pkg"
          curl -fsSL --retry 8 --retry-connrefused ${HOST_TOOLCHAIN_URL} --output swift.pkg
          /usr/sbin/installer -pkg swift.pkg -target CurrentUserHomeDirectory
          SWIFT_PATH=${HOME}/Library/Developer/Toolchains/$(basename ${HOST_TOOLCHAIN_URL} "-osx.pkg").xctoolchain/usr
          ${SWIFT_PATH}/bin/swift --version

          mkdir PackageDemo
          cd PackageDemo
          ${SWIFT_PATH}/bin/swift package init
          ${SWIFT_PATH}/bin/swift test

          ${SWIFT_PATH}/bin/swift sdk install https://download.swift.org/swift-6.2-branch/static-sdk/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-08-09-a/swift-6.2-DEVELOPMENT-SNAPSHOT-2025-08-09-a_static-linux-0.0.1.artifactbundle.tar.gz --checksum 157dbf0cc8465f72c00a765c5f99e24d06c06b71cbe59136421163aa2c0fa7eb



